global:
  slack_api_url: https://hooks.slack.com/services/API_URL_SECRET

route:
  group_by: [cluster]
  # If an alert isn't caught by a route, send it slack.
  receiver: slack-all
  routes:
    - match:
        severity: slack
      receiver: slack-all
    - match:
        severity: slack
      receiver: waroom-all


receivers:
- name: 'slack-all'
  slack_configs:
  - channel: '#meltria-alerts'
    send_resolved: true
    title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
    text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
    api_url: https://hooks.slack.com/services/API_URL_SECRET

- name: 'waroom-all'
  webhook_configs:
    - url: 'https://api.beta.waroom.com/v1/events/alertmanager'
      send_resolved: true
      http_config:
        authorization:
          credentials_file: /alertmanager/waroom-integration-key
