repositories:
  - name: litmuschaos
    url: https://litmuschaos.github.io/litmus-helm/
  - name: argoproj
    url: https://argoproj.github.io/argo-helm

releases:
  - name: chaos
    namespace: litmus
    chart: litmuschaos/litmus
    version: ~2.10.0
    values:
      - mongo:
          nodeSelector:
            cloud.google.com/gke-nodepool: control-pool
      - portal:
          frontend:
            nodeSelector:
              cloud.google.com/gke-nodepool: control-pool
            resources:
              requests:
                cpu: "50m"
                memory: "100Mi"
          server:
            nodeSelector:
              cloud.google.com/gke-nodepool: control-pool
            waitForMongodb:
              resources:
                requests:
                  cpu: "50m"
                  memory: "100Mi"
            graphqlServer:
              resources:
                requests:
                  cpu: "50m"
                  memory: "100Mi"
            authServer:
              resources:
                requests:
                  cpu: "50m"
                  memory: "100Mi"
            mongo:
              resources:
                requests:
                  cpu: "50m"
                  memory: "100Mi"
          upgradeAgent:
            nodeSelector:
              cloud.google.com/gke-nodepool: control-pool
  - name: kubernetes-chaos
    namespace: litmus
    chart: litmuschaos/kubernetes-chaos
    version: ~2.24.0
    values:
      - image:
          litmusGO:
            pullPolicy: IfNotPresent # pullPolicy should be set to 'Always' when chart version updated
  - name: argo-workflows
    namespace: argo
    chart: argoproj/argo-workflows
    version: ~0.16.1
    # https://github.com/argoproj/argo-helm/blob/34e606f012ee81034037ce321dbba989c9c06b16/charts/argo-workflows/values.yaml#L40
    values:
      - controller:
          nodeSelector:
            cloud.google.com/gke-nodepool: control-pool
          image:
            tag: "v3.3.6"
      - executor:
          nodeSelector:
            cloud.google.com/gke-nodepool: control-pool
          image:
            tag: "v3.3.6"
      - server:
          nodeSelector:
            cloud.google.com/gke-nodepool: control-pool
          image:
            tag: "v3.3.6"
