groups:
- name: meltria_sockshop
  rules:
  - alert: LowRequestLatency
    expr: rate(requests{app="owlk8s",ns="sock_shop",svc="front-end"}[1m]) < 280
    for: 20m
    labels:
      severity: slack
    annotations:
      summary: "Low requests rate {{ $labels.svc }} in {{ $labels.ns }}"
      description: "(current value: {{ $value }}[1m])"
