groups:
- name: sli
  rules:
  - alert: LowRequestsRate
    expr: rate(requests{app="owlk8s",ns="sock_shop",svc="front_end"}[1m]) < 295
    for: 20m  # over chaos duration
    labels:
      severity: slack
    annotations:
      summary: "Low requests rate {{ $labels.svc }} in {{ $labels.ns }}"
      description: "{{ $labels.svc }} in {{ $labels.ns }}: {{ $value }} RPS"
