---
apiVersion: v1
kind: Service
metadata:
  name: carts-db
  labels:
    app.kubernetes.io/name: carts-db
    app.kubernetes.io/part-of: carts
    app.kubernetes.io/component: db
    app: sock-shop
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
  - port: 27017
    targetPort: 27017
  selector:
    app.kubernetes.io/name: carts-db
    app.kubernetes.io/part-of: carts
    app.kubernetes.io/component: db
    app: sock-shop
