---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts
  labels:
    app.kubernetes.io/name: carts
    app.kubernetes.io/part-of: carts
    app.kubernetes.io/component: web
    app: sock-shop
    runtime: jvm
  annotations:
    litmuschaos.io/chaos: "true"
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: carts
      app.kubernetes.io/part-of: carts
      app.kubernetes.io/component: web
      app: sock-shop
      runtime: jvm
  template:
    metadata:
      labels:
        app.kubernetes.io/name: carts
        app.kubernetes.io/part-of: carts
        app.kubernetes.io/component: web
        app: sock-shop
        runtime: jvm
    spec:
      containers:
      - name: carts
        image: ghcr.io/ai4sre/sockshop-carts:latest
        env:
          - name: ZIPKIN
            value: zipkin.jaeger.svc.cluster.local
          - name: JAVA_TOOL_OPTIONS
            value: >-
                -XX:+UseContainerSupport
                -XX:MinRAMFraction=2
                -XX:MaxRAMFraction=2
                -XX:+UseG1GC
                -Djava.security.egd=file:/dev/urandom
                -Dcom.sun.management.jmxremote
                -Dcom.sun.management.jmxremote.port=5555
                -Dcom.sun.management.jmxremote.authenticate=false
                -Dcom.sun.management.jmxremote.ssl=false
        resources:
          limits:
            cpu: 1500m
            memory: 1200Mi
          requests:
            cpu: 800m
            memory: 800Mi
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 3
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        beta.kubernetes.io/os: linux
        cloud.google.com/gke-nodepool: "default-pool"
