---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  labels:
    app.kubernetes.io/name: catalogue
    app.kubernetes.io/part-of: catalogue
    app.kubernetes.io/component: web
    app: sock-shop
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    app.kubernetes.io/name: catalogue
    app.kubernetes.io/part-of: catalogue
    app.kubernetes.io/component: web
    app: sock-shop
