---
apiVersion: v1
kind: Service
metadata:
  name: catalogue-db
  labels:
    app.kubernetes.io/name: catalogue-db
    app.kubernetes.io/part-of: catalogue
    app.kubernetes.io/component: db
    app: sock-shop
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
  - port: 3306
    targetPort: 3306
  selector:
    app.kubernetes.io/name: catalogue-db
    app.kubernetes.io/part-of: catalogue
    app.kubernetes.io/component: db
    app: sock-shop
