---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    app.kubernetes.io/name: catalogue
    app.kubernetes.io/part-of: catalogue
    app.kubernetes.io/component: web
    app: sock-shop
    runtime: go
  annotations:
    litmuschaos.io/chaos: "true"
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: catalogue
      app.kubernetes.io/part-of: catalogue
      app.kubernetes.io/component: web
      app: sock-shop
      runtime: go
  template:
    metadata:
      labels:
        app.kubernetes.io/name: catalogue
        app.kubernetes.io/part-of: catalogue
        app.kubernetes.io/component: web
        app: sock-shop
        runtime: go
    spec:
      containers:
      - name: catalogue
        image: weaveworksdemos/catalogue:0.3.5
        command: ["/app"]
        args:
        - -port=80
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 180
          periodSeconds: 3
      nodeSelector:
        beta.kubernetes.io/os: linux
        cloud.google.com/gke-nodepool: "default-pool"
