---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    app.kubernetes.io/name: front-end
    app.kubernetes.io/part-of: front-end
    app.kubernetes.io/component: web
    app: sock-shop
  namespace: sock-shop
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8079
    nodePort: 30002
  selector:
    app.kubernetes.io/name: front-end
    app.kubernetes.io/part-of: front-end
    app.kubernetes.io/component: web
    app: sock-shop
