---
apiVersion: v1
kind: Service
metadata:
  name: orders-db
  labels:
    app.kubernetes.io/name: orders-db
    app.kubernetes.io/part-of: orders
    app.kubernetes.io/component: db
    app: sock-shop
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
  - port: 27017
    targetPort: 27017
  selector:
    app.kubernetes.io/name: orders-db
    app.kubernetes.io/part-of: orders
    app.kubernetes.io/component: db
    app: sock-shop
