---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app.kubernetes.io/name: payment
    app.kubernetes.io/part-of: payment
    app.kubernetes.io/component: web
    app: sock-shop
    runtime: go
  annotations:
    litmuschaos.io/chaos: "true"
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: payment
      app.kubernetes.io/part-of: payment
      app.kubernetes.io/component: web
      app: sock-shop
  template:
    metadata:
      labels:
        app.kubernetes.io/name: payment
        app.kubernetes.io/part-of: payment
        app.kubernetes.io/component: web
        app: sock-shop
    spec:
      containers:
      - name: payment
        image: weaveworksdemos/payment:0.4.3
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 180
          periodSeconds: 3
      nodeSelector:
        beta.kubernetes.io/os: linux
        cloud.google.com/gke-nodepool: "default-pool"
