---
apiVersion: v1
kind: Service
metadata:
  name: queue-master
  labels:
    app.kubernetes.io/name: queue-master
    app.kubernetes.io/part-of: shipping
    app.kubernetes.io/component: queue-web
    app: sock-shop
  annotations:
    prometheus.io/path: "/prometheus"
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    app.kubernetes.io/name: queue-master
    app.kubernetes.io/part-of: shipping
    app.kubernetes.io/component: queue-web
    app: sock-shop
