---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: shipping
    app.kubernetes.io/component: queue-db
    app: sock-shop
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
  - port: 5672
    name: rabbitmq
    targetPort: 5672
  - port: 9090
    name: exporter
    targetPort: exporter
    protocol: TCP
  selector:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: shipping
    app.kubernetes.io/component: queue-db
    app: sock-shop
