---
apiVersion: v1
kind: Service
metadata:
  name: session-db
  labels:
    app.kubernetes.io/name: session-db
    app.kubernetes.io/part-of: front-end
    app.kubernetes.io/component: db
    app: sock-shop
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
  - port: 6379
    targetPort: 6379
  selector:
    app.kubernetes.io/name: session-db
    app.kubernetes.io/part-of: front-end
    app.kubernetes.io/component: db
    app: sock-shop
