---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
  labels:
    app.kubernetes.io/name: user-db
    app.kubernetes.io/part-of: user
    app.kubernetes.io/component: db
    app: sock-shop
  annotations:
    litmuschaos.io/chaos: "true"
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: user-db
      app.kubernetes.io/part-of: user
      app.kubernetes.io/component: db
      app: sock-shop
  template:
    metadata:
      labels:
        app.kubernetes.io/name: user-db
        app.kubernetes.io/part-of: user
        app.kubernetes.io/component: db
        app: sock-shop
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9216"
    spec:
      containers:
      - name: user-db
        image: yuuki/sockshop-user-db:0.3.1
        ports:
        - name: mongo
          containerPort: 27017
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 200m
            memory: 200Mi
      - name: mongodb-exporter
        image: percona/mongodb_exporter:0.32.0
        imagePullPolicy: IfNotPresent
        args: ['--collector.diagnosticdata', '--collector.replicasetstatus', '--collector.dbstats', '--collector.topmetrics', '--collector.indexstats', '--collector.collstats', '--compatible-mode']
        ports:
        - name: exporter
          containerPort: 9216
          protocol: TCP
        env:
          - name: MONGODB_URI
            value: "mongodb://localhost:27017"
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        beta.kubernetes.io/os: linux
        cloud.google.com/gke-nodepool: "default-pool"
