---
apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    app.kubernetes.io/name: user
    app.kubernetes.io/part-of: user
    app.kubernetes.io/component: web
    app: sock-shop
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    app.kubernetes.io/name: user
    app.kubernetes.io/part-of: user
    app.kubernetes.io/component: web
    app: sock-shop
