apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts-db
  namespace: sock-shop
spec:
  template:
    spec:
      containers:
      - name: carts-db
        resources:
          limits:
            cpu: 400m
            memory: 200Mi
          requests:
            cpu: 400m
            memory: 200Mi
