apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-important
spec:
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9216"
    spec:
      containers:
        - name: mongodb-exporter
          image: percona/mongodb_exporter:0.32.0
          imagePullPolicy: IfNotPresent
          ports:
          - name: exporter
            containerPort: 9104
            protocol: TCP
          env:
          - name: MONGODB_URI
            value: "mongodb://localhost:27017"
