apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-ui-dashboard
  labels:
    app.kubernetes.io/name: ts-ui-dashboard
    app.kubernetes.io/component: proxy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ts-ui-dashboard
      app.kubernetes.io/component: proxy
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ts-ui-dashboard
        app.kubernetes.io/component: proxy
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "4040"
    spec:
      containers:
      - name: ts-ui-dashboard
        image: codewisdom/ts-ui-dashboard:0.2.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nginxconfig-vol
          mountPath: /usr/local/openresty/nginx/conf/
        - name: nginxlog-vol
          mountPath: /usr/local/openresty/nginx/logs/
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 500m
            memory: 200Mi
      - name: nginxlog-exporter
        image: ghcr.io/martin-helmich/prometheus-nginxlog-exporter/exporter:v1.9.2
        args: ["-config-file", "/etc/prometheus-nginxlog-exporter/nginxlog-exporter.config.hcl"]
        ports:
          - name: exporter
            containerPort: 4040
        volumeMounts:
        - name: nginxlog-vol
          mountPath: /etc/nginxlog
        - name: nginxlog-exporter-config
          mountPath: /etc/prometheus-nginxlog-exporter
      volumes:
      - name: nginxconfig-vol
        configMap:
          name: nginx-config
      - name: nginxlog-vol
        emptyDir: {}
      - name: nginxlog-exporter-config
        configMap:
          name: nginxlog-exporter-config

---

apiVersion: v1
kind: Service
metadata:
  name: ts-ui-dashboard
  labels:
    app.kubernetes.io/name: ts-ui-dashboard
    app.kubernetes.io/component: proxy
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      nodePort: 32677
  selector:
    app.kubernetes.io/name: ts-ui-dashboard
    app.kubernetes.io/component: proxy
---
