#!/bin/bash

set -e -o pipefail

appNamespace=$1
appLabel=$2
chaos=$3
debug=$4

cleanup='delete'
if [[ ${debug} != "" ]]; then
  cleanup='retain'
fi

cue eval --out yaml argowf-chaos.cue | argo submit -n litmus --watch --parameter appNamespace="${appNamespace}" --parameter chaosTypes="'${chaos}'" --parameter appLabels="[\"${appLabel}\"]" --parameter litmusJobCleanupPolicy="${cleanup}" -
