#!/bin/bash

set -e -o pipefail

appLabel=$1
chaos=$2
debug=$3

cleanup='delete'
if [[ debug != "" ]]; then
  cleanup='retain'
fi

cue eval --out yaml argowf-chaos.cue | argo submit -n litmus --watch --parameter chaosTypes="'$2'" --parameter appLabels="[\"$1\"]" --parameter litmusJobCleanupPolicy="${cleanup}" -
