apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-test
  labels:
    name: load-test
  namespace: loadtest
spec:
  replicas: 2
  selector:
    matchLabels:
      name: load-test
  template:
    metadata:
      labels:
        name: load-test
    spec:
      containers:
      - name: load-test
        image: locustio/locust:2.9.0
        command: ["/bin/sh"]
        # locust log: 'Your selected spawn rate is very high (>100), and this is known to sometimes cause issues. Do you really need to ramp up that fast?'
        args: ["-c", "while true; do locust --host http://ts-ui-dashboard.train-ticket.svc.cluster.local:8080 -f /config/locustfile.py --headless --users $(LOCUST_USERS) --spawn-rate $(LOCUST_SPAWN_RATE) --run-time 30s --only-summary; done"]
        volumeMounts:
          - name: locustfile-volume
            mountPath: /config
        env:
          - name: LOCUST_USERS
            value: '5'
          - name: LOCUST_SPAWN_RATE
            value: '5'
      volumes:
        - name: locustfile-volume
          configMap:
            name: locustfile
      nodeSelector:
        kubernetes.io/os: linux
        cloud.google.com/gke-nodepool: "control-pool"
