apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-test-master
  labels:
    app: load-test-master
    app.kubernetes.io/name: load-test-master
    app.kubernetes.io/parts-of: load-test-cluster
    app.kubernetes.io/component: locust-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-test-master
      app.kubernetes.io/name: load-test-master
      app.kubernetes.io/parts-of: load-test-cluster
      app.kubernetes.io/component: locust-master
  template:
    metadata:
      labels:
        app: load-test-master
        app.kubernetes.io/name: load-test-master
        app.kubernetes.io/parts-of: load-test-cluster
        app.kubernetes.io/component: locust-master
    spec:
      containers:
      - name: load-test-master
        image: locustio/locust:2.9.0
        args: ["-f", "/config/locustfile.py", "--master"]
        volumeMounts:
          - name: locustfile-volume
            mountPath: /config
        env:
          - name: PATHONPATH  # to load locustfile_dataset.py
            value: /config
          - name: LOCUST_VERBOSE_LOGGING
            value: 'false'
          - name: LOCUST_HOST
            value: 'http://ts-ui-dashboard.train-ticket.svc.cluster.local:8080'
          - name: LOCUST_USERS
            value: '7'
          - name: LOCUST_SPAWN_RATE
            value: '1'
          - name: LOCUST_AUTOSTART
            value: 'true'
        ports:
          - name: master-web
            containerPort: 8089
            protocol: TCP
          - name: master-p1
            containerPort: 5557
            protocol: TCP
      volumes:
        - name: locustfile-volume
          configMap:
            name: locustfile
      nodeSelector:
        kubernetes.io/os: linux
        cloud.google.com/gke-nodepool: "load-pool"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-test-worker
  labels:
    app: load-test-worker
    app.kubernetes.io/name: load-test-worker
    app.kubernetes.io/parts-of: load-test-cluster
    app.kubernetes.io/component: locust-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-test-worker
      app.kubernetes.io/name: load-test-worker
      app.kubernetes.io/parts-of: load-test-cluster
      app.kubernetes.io/component: locust-worker
  template:
    metadata:
      labels:
        app: load-test-worker
        app.kubernetes.io/name: load-test-worker
        app.kubernetes.io/parts-of: load-test-cluster
        app.kubernetes.io/component: locust-worker
    spec:
      containers:
      - name: load-test-worker
        image: locustio/locust:2.9.0
        args: ["-f", "/config/locustfile.py", "--worker"]
        volumeMounts:
          - name: locustfile-volume
            mountPath: /config
        env:
          - name: LOCUST_MASTER_NODE_HOST
            value: 'load-test-master.loadtest.svc.cluster.local'
      volumes:
        - name: locustfile-volume
          configMap:
            name: locustfile
      nodeSelector:
        kubernetes.io/os: linux
        cloud.google.com/gke-nodepool: "load-pool"
