apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-test
  labels:
    name: load-test
  namespace: loadtest
spec:
  template:
    spec:
      containers:
      - name: load-test
        env:
          - name: LOCUST_USERS
            value: '500'
          - name: LOCUST_SPAWN_RATE
            value: '1'
