{
 "title": "Sock-Shop Performance2",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Service Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Frontend QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops", "label": "QPS (1 min)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count{app_kubernetes_io_name=\"front-end\",status_code=~\"2..\",route!=\"metrics\"}[1m])) * 100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(request_duration_seconds_count{app_kubernetes_io_name=\"front-end\",status_code=~\"4.+|5.+\"}[1m])) * 100",
     "legendFormat": "4xx/5xx"
    }
   ]
  },
  {
   "title": "Frontend latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket{app_kubernetes_io_name=\"front-end\"}[1m])) by (name, le))",
     "legendFormat": "99th quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_duration_seconds_bucket{app_kubernetes_io_name=\"front-end\"}[1m])) by (name, le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "sum(rate(request_duration_seconds_sum{app_kubernetes_io_name=\"front-end\"}[1m])) / sum(rate(request_duration_seconds_count{app_kubernetes_io_name=\"front-end\"}[1m]))",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Catalogue QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ops", "label": "QPS (1 min)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count{app_kubernetes_io_name=\"catalogue\",status_code=~\"2..\",route!=\"metrics\"}[1m])) * 100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(request_duration_seconds_count{app_kubernetes_io_name=\"catalogue\",status_code=~\"4.+|5.+\"}[1m])) * 100",
     "legendFormat": "4xx/5xx"
    }
   ]
  },
  {
   "title": "Catalogue latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket{app_kubernetes_io_name=\"catalogue\"}[1m])) by (name, le))",
     "legendFormat": "99th quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_duration_seconds_bucket{app_kubernetes_io_name=\"catalogue\"}[1m])) by (name, le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "sum(rate(request_duration_seconds_sum{app_kubernetes_io_name=\"catalogue\"}[1m])) / sum(rate(request_duration_seconds_count{app_kubernetes_io_name=\"catalogue\"}[1m]))",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Cart QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ops", "label": "QPS (1 min)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{app_kubernetes_io_name=\"carts\",status_code=~\"2..\",route!=\"metrics\"}[1m])) * 100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{app_kubernetes_io_name=\"carts\",status_code=~\"4.+|5.+\"}[1m])) * 100",
     "legendFormat": "4xx/5xx"
    }
   ]
  },
  {
   "title": "Cart latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{app_kubernetes_io_name=\"carts\"}[1m])) by (name, le))",
     "legendFormat": "99th quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{app_kubernetes_io_name=\"carts\"}[1m])) by (name, le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{app_kubernetes_io_name=\"carts\"}[1m])) / sum(rate(http_request_duration_seconds_count{app_kubernetes_io_name=\"carts\"}[1m]))",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Orders QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "ops", "label": "QPS (1 min)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{app_kubernetes_io_name=\"orders\",status_code=~\"2..\",route!=\"metrics\"}[1m])) * 100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{app_kubernetes_io_name=\"orders\",status_code=~\"4.+|5.+\"}[1m])) * 100",
     "legendFormat": "4xx/5xx"
    }
   ]
  },
  {
   "title": "Orders latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{app_kubernetes_io_name=\"orders\"}[1m])) by (name, le))",
     "legendFormat": "99th quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{app_kubernetes_io_name=\"orders\"}[1m])) by (name, le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "sum(rate(request_duration_seconds_sum{app_kubernetes_io_name=\"orders\"}[1m])) / sum(rate(request_duration_seconds_count{app_kubernetes_io_name=\"orders\"}[1m]))",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Payment QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "ops", "label": "QPS (1 min)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count{app_kubernetes_io_name=\"payment\",status_code=~\"2..\",route!=\"metrics\"}[1m])) * 100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(request_duration_seconds_count{app_kubernetes_io_name=\"payment\",status_code=~\"4.+|5.+\"}[1m])) * 100",
     "legendFormat": "4xx/5xx"
    }
   ]
  },
  {
   "title": "Payment latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket{app_kubernetes_io_name=\"payment\"}[1m])) by (name, le))",
     "legendFormat": "99th quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_duration_seconds_bucket{app_kubernetes_io_name=\"payment\"}[1m])) by (name, le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "sum(rate(request_duration_seconds_sum{app_kubernetes_io_name=\"payment\"}[1m])) / sum(rate(request_duration_seconds_count{app_kubernetes_io_name=\"payment\"}[1m]))",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Shipping QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "ops", "label": "QPS (1 min)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count{app_kubernetes_io_name=\"shipping\",status_code=~\"2..\",route!=\"metrics\"}[1m])) * 100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(request_duration_seconds_count{app_kubernetes_io_name=\"shipping\",status_code=~\"4.+|5.+\"}[1m])) * 100",
     "legendFormat": "4xx/5xx"
    }
   ]
  },
  {
   "title": "Shipping latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket{app_kubernetes_io_name=\"shipping\"}[1m])) by (name, le))",
     "legendFormat": "99th quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_duration_seconds_bucket{app_kubernetes_io_name=\"shipping\"}[1m])) by (name, le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "sum(rate(request_duration_seconds_sum{app_kubernetes_io_name=\"shipping\"}[1m])) / sum(rate(request_duration_seconds_count{app_kubernetes_io_name=\"shipping\"}[1m]))",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "User QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "ops", "label": "QPS (1 min)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count{app_kubernetes_io_name=\"user\",status_code=~\"2..\",route!=\"metrics\"}[1m])) * 100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(request_duration_seconds_count{app_kubernetes_io_name=\"user\",status_code=~\"4.+|5.+\"}[1m])) * 100",
     "legendFormat": "4xx/5xx"
    }
   ]
  },
  {
   "title": "User latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket{app_kubernetes_io_name=\"user\"}[1m])) by (name, le))",
     "legendFormat": "99th quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_duration_seconds_bucket{app_kubernetes_io_name=\"user\"}[1m])) by (name, le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "sum(rate(request_duration_seconds_sum{app_kubernetes_io_name=\"user\"}[1m])) / sum(rate(request_duration_seconds_count{app_kubernetes_io_name=\"user\"}[1m]))",
     "legendFormat": "Mean"
    }
   ]
  },
  { "title": "Container Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"sock-shop\"}[1m])) by (container)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Memory Working set",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",namespace=~\"^sock-shop\"}) by (container)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Network Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "Bps", "label": "transmit / receive" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_network_receive_bytes_total{image!=\"\",namespace=~\"sock-shop\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }} < in"
    },
    {
     "expr": "sum (rate(container_network_transmit_bytes_total{image!=\"\",namespace=~\"sock-shop\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }} > out"
    }
   ]
  },
  {
   "title": "Network packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_network_receive_packets_total{image!=\"\",namespace=~\"sock-shop\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Disk Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{namespace=\"sock-shop\"}[1m])) by (container)",
     "legendFormat": "{{ container}}(r) "
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{namespace=\"sock-shop\"}[1m])) by (container)",
     "legendFormat": "{{ container }}(w)"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_total{image!=\"\",namespace=\"sock-shop\"}[1m])) by (container)",
     "legendFormat": "{{ container }}(r)"
    },
    {
     "expr": "sum(rate(container_fs_writes_total{image!=\"\",namespace=\"sock-shop\"}[1m])) by (container)",
     "legendFormat": "{{ container }}(w)"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{image!=\"\",namespace=~\"sock-shop\"}) by (container)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_errors_total{namespace=\"sock-shop\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }} < in"
    },
    {
     "expr": "sum(rate(container_network_transmit_errors_total{namespace=\"sock-shop\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }} > out"
    },
    {
     "expr": "sum(rate(container_fs_limit_bytes{namespace=\"sock-shop\"}[1m])) by (container)",
     "legendFormat": "{{ container }} limit_bytes"
    },
    {
     "expr": "sum(container_memory_failure_cnt{namespace=\"sock-shop\"}) by (container)",
     "legendFormat": "{{ container }} memory"
    }
   ]
  },
  { "title": "Container Metrics (Middleware)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "MongoDB Document Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (app_kubernetes_io_name) (rate(mongodb_ss_metrics_document [1m]))",
     "legendFormat": "{{ app_kubernetes_io_name }}"
    }
   ]
  },
  {
   "title": "MongoDB Scanned and Moved Objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (app_kubernetes_io_name, state) (rate(mongodb_mongod_metrics_query_executor_total[1m]))",
     "legendFormat": "{{ app_kubernetes_io_name }}:{{ state }}"
    },
    {
     "expr": "sum by (app_kubernetes_io_name, state) (rate(mongodb_mongod_metrics_record_moves_total[1m]))",
     "legendFormat": "{{ app_kubernetes_io_name }}:moved"
    }
   ]
  },
  {
   "title": "MongoDB  getLastError Write Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (app_kubernetes_io_name) (rate(mongodb_mongod_metrics_get_last_error_wtime_total_milliseconds[1m]))",
     "legendFormat": "Write Wait Time {{ app_kubernetes_io_name }}"
    }
   ]
  },
  {
   "title": "Assert Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "yaxes": [
    { "format": "Misc" }
   ],
   "targets": [
    {
     "expr": "sum by (app_kubernetes_io_name, assert_type) (rate(mongodb_ss_asserts[1m]))",
     "legendFormat": "{{assert_type}}"
    }
   ]
  },
  {
   "title": "MySQL connection errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_connection_errors_total[1m])"
    }
   ]
  },
  { "title": "Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (node)(rate(node_cpu_seconds_total{mode=~\"user|system|iowait|.*irq\",kubernetes_pod_name=~\"node-exporter-.*\"}[1m])) * 100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{kubernetes_pod_name=~\"node-exporter-.*\"} - node_memory_MemFree_bytes{kubernetes_pod_name=~\"node-exporter-.*\"} - (node_memory_Cached_bytes{kubernetes_pod_name=~\"node-exporter-.*\"} + node_memory_Buffers_bytes{kubernetes_pod_name=~\"node-exporter-.*\"})) / node_memory_MemTotal_bytes{kubernetes_pod_name=~\"node-exporter-.*\"} * 100",
     "legendFormat": "Ram Used: {{ node }}"
    },
    { "legendFormat": "Ram Total {{ node }}" }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (rate(node_network_receive_bytes_total{kubernetes_pod_name=~\"node-exporter-.*\"}[1m]))",
     "legendFormat": "{{ node }} < in"
    },
    {
     "expr": "sum by (node) (rate(node_network_transmit_bytes_total{kubernetes_pod_name=~\"node-exporter-.*\"}[1m]))",
     "legendFormat": "{{ node }} > out"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (rate(node_disk_reads_completed_total{kubernetes_pod_name=~\"node-exporter-.*\"}[1m]))",
     "legendFormat": "{{ node }} (r)"
    },
    {
     "expr": "sum by (node) (rate(node_disk_writes_completed_total{kubernetes_pod_name=~\"node-exporter-.*\"}[1m]))",
     "legendFormat": "{{ node }} (w)"
    }
   ]
  }
 ]
}