{
 "title": "Sock-Shop Analytics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "# Orders",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "request_duration_seconds_count{name=\"orders\",method=\"POST\"}"
    }
   ]
  },
  {
   "title": "Projected number of orders per day",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(request_duration_seconds_count{name=\"orders\",method=\"POST\"}[1h]) *24*60*60"
    }
   ]
  },
  {
   "title": "# Logins",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "request_duration_seconds_count{name=\"user\", route=\"login\",status_code=\"200\"}"
    }
   ]
  }
 ]
}