[tool.poetry]
name = "metrics"
version = "0.1.0"
description = ""
authors = ["Yuuki Tsubouchi <yuki.tsubo@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
urllib3 = "^1.26.9"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
